# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2735ea998c26b116ecb274c69a19f6edd6205e2b500a10075cef83cee1246b169f63a1ffb5a7449c125d46ce89ecd1e149fa6f249053afe47ca4cc53d9f325af

test:
  secret_key_base: 5d0d940dbb3fc7241c39bf5d65605232f43dce646d60174f9c366173a083fb877df4c94c24d9bf28a770e7a1495e4fd7ee2c8f1dec0f29f5287c02bc218c3702

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
